In [1]:
import numpy as np
import pandas as pd
import pickle
import json

In [2]:
with open('artifacts/gscv_lasso_model.pkl','rb') as f:
    model = pickle.load(f)

In [3]:
model

RandomizedSearchCV(cv=5, estimator=Lasso(alpha=1),
                   param_distributions={'alpha': array([0.05 , 0.051, 0.052, ..., 1.997, 1.998, 1.999])})

In [4]:
array = np.zeros((1,model.n_features_in_))

In [5]:
with open('artifacts/project_data.json') as f:
    project_data = json.load(f)
project_data

{'Column Names': ['work_year',
  'experience_level',
  'employment_type',
  'salary',
  'remote_ratio',
  'company_size',
  'job_title_3D Computer Vision Researcher',
  'job_title_AI Scientist',
  'job_title_Applied Data Scientist',
  'job_title_Applied Machine Learning Scientist',
  'job_title_BI Data Analyst',
  'job_title_Big Data Architect',
  'job_title_Big Data Engineer',
  'job_title_Business Data Analyst',
  'job_title_Cloud Data Engineer',
  'job_title_Computer Vision Engineer',
  'job_title_Computer Vision Software Engineer',
  'job_title_Data Analyst',
  'job_title_Data Analytics Engineer',
  'job_title_Data Analytics Manager',
  'job_title_Data Architect',
  'job_title_Data Engineer',
  'job_title_Data Engineering Manager',
  'job_title_Data Science Consultant',
  'job_title_Data Science Engineer',
  'job_title_Data Science Manager',
  'job_title_Data Scientist',
  'job_title_Data Specialist',
  'job_title_Director of Data Engineering',
  'job_title_Director of Data Science',
  'job_title_Finance Data Analyst',
  'job_title_Financial Data Analyst',
  'job_title_Head of Data',
  'job_title_Head of Data Science',
  'job_title_Lead Data Analyst',
  'job_title_Lead Data Engineer',
  'job_title_Lead Data Scientist',
  'job_title_ML Engineer',
  'job_title_Machine Learning Engineer',
  'job_title_Machine Learning Infrastructure Engineer',
  'job_title_Machine Learning Scientist',
  'job_title_Manager Data Science',
  'job_title_Marketing Data Analyst',
  'job_title_Principal Data Analyst',
  'job_title_Principal Data Engineer',
  'job_title_Principal Data Scientist',
  'job_title_Product Data Analyst',
  'job_title_Research Scientist',
  'job_title_Staff Data Scientist',
  'salary_currency_BRL',
  'salary_currency_CAD',
  'salary_currency_CLP',
  'salary_currency_CNY',
  'salary_currency_DKK',
  'salary_currency_EUR',
  'salary_currency_GBP',
  'salary_currency_HUF',
  'salary_currency_INR',
  'salary_currency_JPY',
  'salary_currency_MXN',
  'salary_currency_PLN',
  'salary_currency_SGD',
  'salary_currency_TRY',
  'salary_currency_USD',
  'employee_residence_AE',
  'employee_residence_AT',
  'employee_residence_BE',
  'employee_residence_BG',
  'employee_residence_BR',
  'employee_residence_CA',
  'employee_residence_CL',
  'employee_residence_CN',
  'employee_residence_CO',
  'employee_residence_DE',
  'employee_residence_DK',
  'employee_residence_ES',
  'employee_residence_FR',
  'employee_residence_GB',
  'employee_residence_GR',
  'employee_residence_HK',
  'employee_residence_HR',
  'employee_residence_HU',
  'employee_residence_IN',
  'employee_residence_IR',
  'employee_residence_IT',
  'employee_residence_JE',
  'employee_residence_JP',
  'employee_residence_KE',
  'employee_residence_LU',
  'employee_residence_MD',
  'employee_residence_MT',
  'employee_residence_MX',
  'employee_residence_NG',
  'employee_residence_NL',
  'employee_residence_NZ',
  'employee_residence_PH',
  'employee_residence_PK',
  'employee_residence_PL',
  'employee_residence_PR',
  'employee_residence_PT',
  'employee_residence_RO',
  'employee_residence_RS',
  'employee_residence_RU',
  'employee_residence_SG',
  'employee_residence_SI',
  'employee_residence_TR',
  'employee_residence_UA',
  'employee_residence_US',
  'employee_residence_VN',
  'company_location_AE',
  'company_location_AS',
  'company_location_AT',
  'company_location_BE',
  'company_location_BR',
  'company_location_CA',
  'company_location_CH',
  'company_location_CL',
  'company_location_CN',
  'company_location_CO',
  'company_location_DE',
  'company_location_DK',
  'company_location_ES',
  'company_location_FR',
  'company_location_GB',
  'company_location_GR',
  'company_location_HR',
  'company_location_HU',
  'company_location_IL',
  'company_location_IN',
  'company_location_IR',
  'company_location_IT',
  'company_location_JP',
  'company_location_KE',
  'company_location_LU',
  'company_location_MD',
  'company_location_MT',
  'company_location_MX',
  'company_location_NG',
  'company_location_NL',
  'company_location_NZ',
  'company_location_PK',
  'company_location_PL',
  'company_location_PT',
  'company_location_RU',
  'company_location_SG',
  'company_location_SI',
  'company_location_TR',
  'company_location_UA',
  'company_location_US',
  'company_location_VN'],
 'work_year': {'2021e': 2021, '2020': 2020},
 'experience_level': {'MI': 103, 'SE': 77, 'EN': 54, 'EX': 11},
 'employment_type': {'FT': 231, 'PT': 7, 'CT': 4, 'FL': 3},
 'company_size': {'L': 132, 'S': 58, 'M': 55}}

In [6]:
work_year = '2020'
experience_level = 'EN'
employment_type = 'FT'
job_title = 'Data Scientist'
salary =58000
salary_currency = 'EUR'
employee_residence = 'DE'
remote_ratio = 50
company_location ='DE'
company_size ='L'

In [7]:
model.feature_names_in_

array(['work_year', 'experience_level', 'employment_type', 'salary',
       'remote_ratio', 'company_size',
       'job_title_3D Computer Vision Researcher',
       'job_title_AI Scientist', 'job_title_Applied Data Scientist',
       'job_title_Applied Machine Learning Scientist',
       'job_title_BI Data Analyst', 'job_title_Big Data Architect',
       'job_title_Big Data Engineer', 'job_title_Business Data Analyst',
       'job_title_Cloud Data Engineer',
       'job_title_Computer Vision Engineer',
       'job_title_Computer Vision Software Engineer',
       'job_title_Data Analyst', 'job_title_Data Analytics Engineer',
       'job_title_Data Analytics Manager', 'job_title_Data Architect',
       'job_title_Data Engineer', 'job_title_Data Engineering Manager',
       'job_title_Data Science Consultant',
       'job_title_Data Science Engineer',
       'job_title_Data Science Manager', 'job_title_Data Scientist',
       'job_title_Data Specialist',
       'job_title_Director of Data Engineering',
       'job_title_Director of Data Science',
       'job_title_Finance Data Analyst',
       'job_title_Financial Data Analyst', 'job_title_Head of Data',
       'job_title_Head of Data Science', 'job_title_Lead Data Analyst',
       'job_title_Lead Data Engineer', 'job_title_Lead Data Scientist',
       'job_title_ML Engineer', 'job_title_Machine Learning Engineer',
       'job_title_Machine Learning Infrastructure Engineer',
       'job_title_Machine Learning Scientist',
       'job_title_Manager Data Science',
       'job_title_Marketing Data Analyst',
       'job_title_Principal Data Analyst',
       'job_title_Principal Data Engineer',
       'job_title_Principal Data Scientist',
       'job_title_Product Data Analyst', 'job_title_Research Scientist',
       'job_title_Staff Data Scientist', 'salary_currency_BRL',
       'salary_currency_CAD', 'salary_currency_CLP',
       'salary_currency_CNY', 'salary_currency_DKK',
       'salary_currency_EUR', 'salary_currency_GBP',
       'salary_currency_HUF', 'salary_currency_INR',
       'salary_currency_JPY', 'salary_currency_MXN',
       'salary_currency_PLN', 'salary_currency_SGD',
       'salary_currency_TRY', 'salary_currency_USD',
       'employee_residence_AE', 'employee_residence_AT',
       'employee_residence_BE', 'employee_residence_BG',
       'employee_residence_BR', 'employee_residence_CA',
       'employee_residence_CL', 'employee_residence_CN',
       'employee_residence_CO', 'employee_residence_DE',
       'employee_residence_DK', 'employee_residence_ES',
       'employee_residence_FR', 'employee_residence_GB',
       'employee_residence_GR', 'employee_residence_HK',
       'employee_residence_HR', 'employee_residence_HU',
       'employee_residence_IN', 'employee_residence_IR',
       'employee_residence_IT', 'employee_residence_JE',
       'employee_residence_JP', 'employee_residence_KE',
       'employee_residence_LU', 'employee_residence_MD',
       'employee_residence_MT', 'employee_residence_MX',
       'employee_residence_NG', 'employee_residence_NL',
       'employee_residence_NZ', 'employee_residence_PH',
       'employee_residence_PK', 'employee_residence_PL',
       'employee_residence_PR', 'employee_residence_PT',
       'employee_residence_RO', 'employee_residence_RS',
       'employee_residence_RU', 'employee_residence_SG',
       'employee_residence_SI', 'employee_residence_TR',
       'employee_residence_UA', 'employee_residence_US',
       'employee_residence_VN', 'company_location_AE',
       'company_location_AS', 'company_location_AT',
       'company_location_BE', 'company_location_BR',
       'company_location_CA', 'company_location_CH',
       'company_location_CL', 'company_location_CN',
       'company_location_CO', 'company_location_DE',
       'company_location_DK', 'company_location_ES',
       'company_location_FR', 'company_location_GB',
       'company_location_GR', 'company_location_HR',
       'company_location_HU', 'company_location_IL',
       'company_location_IN', 'company_location_IR',
       'company_location_IT', 'company_location_JP',
       'company_location_KE', 'company_location_LU',
       'company_location_MD', 'company_location_MT',
       'company_location_MX', 'company_location_NG',
       'company_location_NL', 'company_location_NZ',
       'company_location_PK', 'company_location_PL',
       'company_location_PT', 'company_location_RU',
       'company_location_SG', 'company_location_SI',
       'company_location_TR', 'company_location_UA',
       'company_location_US', 'company_location_VN'], dtype=object)

In [8]:
array[0][0] = project_data['work_year'][work_year]
array[0][1] = project_data['experience_level'][experience_level]
array[0][2] = project_data['employment_type'][employment_type]


print(job_title)
job_title ='job_title_' + job_title 
index = project_data['Column Names'].index(job_title)
array[0][index] = 1

array[0][3] = salary








print(salary_currency)
salary_currency='salary_currency_'+salary_currency
index = project_data['Column Names'].index(salary_currency)
array[0][index] = 1




print(employee_residence)
employee_residence='employee_residence_'+ employee_residence
index = project_data['Column Names'].index(employee_residence)
array[0][index] = 1


array[0][4] = remote_ratio


print(company_location)
company_location ='company_location_' + company_location 
index = project_data['Column Names'].index(company_location)
array[0][index] = 1



array[0][5] = project_data['company_size'][company_size]

Data Scientist
EUR
DE
DE

In [9]:
test_df = pd.DataFrame(array,columns=model.feature_names_in_)

In [10]:
test_df

,work_year,experience_level,employment_type,salary,remote_ratio,company_size,job_title_3D Computer Vision Researcher,job_title_AI Scientist,job_title_Applied Data Scientist,job_title_Applied Machine Learning Scientist,...,company_location_PK,company_location_PL,company_location_PT,company_location_RU,company_location_SG,company_location_SI,company_location_TR,company_location_UA,company_location_US,company_location_VN
0,2020.0,54.0,231.0,58000.0,50.0,132.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
model.predict(test_df)[0]

1475765.6977046486